apiVersion: apps/v1
kind: Deployment
metadata:
  name: market
  namespace: default
  labels:
    app: market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market
  template:
    metadata:
      labels:
        app: market
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "market"
        dapr.io/app-port: "8086"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: market
          image: ghcr.io/azhovan/market:v0.7
---